=== SuHu0426/KMLN/DTD/kmln.dtd
<!ELEMENT project (global, default?, (switch|superclass)*)>

<!ELEMENT global EMPTY>
<!ATTLIST global
projName CDATA #REQUIRED
>

<!ELEMENT default (host)+>

<!ELEMENT switch EMPTY>
<!ATTLIST switch
name ID #REQUIRED
physical_host CDATA #IMPLIED
switchType (uml|vde|ovs) "ovs"
vde CDATA #IMPLIED
ovs CDATA #IMPLIED
owner CDATA #IMPLIED
tap CDATA #IMPLIED
tun_iface CDATA #IMPLIED
tun_address CDATA #IMPLIED
>

<!ELEMENT superclass (network*,users?,groups?,host+) >
<!ATTLIST superclass
name ID #REQUIRED
term (xterm|screen|monitor|vnc|spice) "screen"
color CDATA #IMPLIED
template CDATA #IMPLIED
filesystem CDATA #IMPLIED
swap CDATA #IMPLIED
size CDATA #IMPLIED
free_space CDATA #IMPLIED
qcow (qcow|qcow2|raw) #IMPLIED
cow_filesystem CDATA #IMPLIED
format (ext2|ext3|ext4) #IMPLIED
memory CDATA "64MB"
vcpu CDATA "1" 
physical_host CDATA #IMPLIED
virTech (kvm|uml|xen) "kvm"
kernel CDATA #IMPLIED
modules CDATA #IMPLIED
kvm CDATA #IMPLIED
root_password CDATA #IMPLIED
boot_order CDATA #IMPLIED
nice CDATA #IMPLIED
owner CDATA #IMPLIED
sudo CDATA #IMPLIED
users CDATA #IMPLIED
group CDATA #IMPLIED
family (busybox|debian|redhat|windows|suse) "debian"
vncport CDATA "1"
vncpass CDATA #IMPLIED
>

<!ELEMENT host (network*,users?,groups?)>
<!ATTLIST host
name ID #REQUIRED
term (xterm|screen|monitor|vnc|spice) #IMPLIED
color CDATA #IMPLIED
template CDATA #IMPLIED
filesystem CDATA #IMPLIED
swap CDATA #IMPLIED
size CDATA #IMPLIED
free_space CDATA #IMPLIED
qcow (qcow|qcow2|raw) #IMPLIED
cow_filesystem CDATA #IMPLIED
format (ext2|ext3|ext4) #IMPLIED
memory CDATA #IMPLIED
vcpu CDATA #IMPLIED
physical_host CDATA #IMPLIED
virTech (kvm|uml|xen) #IMPLIED
kernel CDATA #IMPLIED
modules CDATA #IMPLIED
kvm CDATA #IMPLIED
root_password CDATA #IMPLIED
boot_order CDATA #IMPLIED
nice CDATA #IMPLIED
owner CDATA #IMPLIED
sudo CDATA #IMPLIED
group CDATA #IMPLIED
family (busybox|debian|redhat|windows|suse) #IMPLIED
vncport CDATA #IMPLIED
vncpass CDATA #IMPLIED
>

<!ELEMENT network EMPTY>
<!ATTLIST network
name CDATA #REQUIRED
switch IDREF #IMPLIED
netmask CDATA #IMPLIED
gateway CDATA #IMPLIED
address CDATA #IMPLIED
broadcast CDATA #IMPLIED
mac CDATA #IMPLIED
auto CDATA #IMPLIED
>

<!ELEMENT users (user*)>
<!ELEMENT user EMPTY>
<!ATTLIST user
username CDATA #REQUIRED
password CDATA #IMPLIED>

<!ELEMENT groups (group*)>
<!ELEMENT group (groupuser+)>
<!ATTLIST group
groupname CDATA #REQUIRED
>
<!ELEMENT groupuser EMPTY>
<!ATTLIST groupuser
user CDATA #REQUIRED
>

=== SuHu0426/KMLN/examples/kvm-qcow2.xml
<?xml version="1.0"?>
<!DOCTYPE project SYSTEM "/etc/mln/DTD/kmln.dtd">
<project>
  <global projName="CTSP-cloud" />
  
  <switch name="lan1"
	  switchType="vde"
	  owner="cloud"
	  tap="tap-ctsp"
	  tun_iface="eth1"
	  tun_address="192.168.0.1"
	  physical_host="CSIE-Cloud01"
	  />

  <switch name="lan2"
          switchType="vde"
          owner="cloud"
          tap="tap-ctsp"
          tun_iface="eth1"
          tun_address="192.168.0.2"
	  physical_host="CSIE-Cloud02"
          />

  <superclass name="cloud01"
    term="screen"
    virTech="kvm"
    template="DebSqz-mln.img"
    size="4096M"
    memory="256M"
    qcow="qcow2"
    physical_host="CSIE-Cloud01"
    >
    <network name="eth0"
	     switch="lan1"
	     netmask="255.255.255.0"
	     gateway="192.168.0.1"
	     />
    <host name="ctsp01-1">
      <network name="eth0" address="192.168.0.131"/>
    </host>  
    <host name="ctsp01-2">
      <network name="eth0" address="192.168.0.132"/>
    </host>

  </superclass>

  <superclass name="cloud02"
    term="screen"
    virTech="kvm"
    template="DebSqz-mln.img"
    size="4096M"
    memory="256M"
    qcow="qcow2"
    physical_host="CSIE-Cloud02"
    >
    <network name="eth0"
      switch="lan2"
      netmask="255.255.255.0"
      gateway="192.168.0.2"
      />
    <host name="ctsp11-1">
      <network name="eth0" address="192.168.0.171"/>
    </host>  
    <host name="ctsp11-2">
      <network name="eth0" address="192.168.0.172"/>
    </host>

  </superclass>
</project>

=== SuHu0426/KMLN/examples/vde-kvm+uml.xml
<?xml version="1.0"?>
<!DOCTYPE project SYSTEM "/etc/mln/DTD/kmln.dtd">
<project>
  <global projName="vde-kvm+uml" />
  
  <switch name="lan0"
	  switchType="vde"
	  owner="jssu"
	  tap="tap0"
	  tun_iface="eth1"
	  tun_address="192.168.0.1"
	  />

  <switch name="lan1"
          switchType="vde"
          owner="jssu"
          tap="tap0"
          tun_iface="eth1"
          tun_address="192.168.0.2"
          />

  <superclass name="uml"
              term="screen"
              virTech="uml"
              modules="/usr/local/lib/uml/lib/modules/3.0.0/"
              template="DebSqz-UltraLight.ext3"
              size="500M"
              memory="256M"
              >
    <network name="eth0"
             switch="lan0"
             netmask="255.255.255.0"
             gateway="192.168.0.1"
             />
    <host name="uml-01">
      <network name="eth0" address="192.168.0.101"/>
    </host>  
  </superclass>

  <superclass name="kvm"
	      term="screen"
	      virTech="kvm"
	      template="DebSqz-mini.img"
	      size="800M"
	      memory="256M"
	      >
    <network name="eth0"
	     switch="lan1"
	     netmask="255.255.255.0"
	     gateway="192.168.0.1"
	     />
    <host name="kvm-01">
      <network name="eth0" address="192.168.0.102"/>
    </host>  
  </superclass>

</project>

=== SuHu0426/KMLN/examples/msc2.xml
<?xml version="1.0"?>
<!DOCTYPE project SYSTEM "/etc/mln/DTD/kmln.dtd">
<project>
  <global projName="msc2" />

  <switch name="banana-entrance"
          switchType="ovs"
          owner="hsu"
          tap="tapovs61"
          tun_iface="br1"
          tun_address="140.120.15.171"
          physical_host="banana"
          />
  <switch name="banana-POX1"
          switchType="ovs"
          owner="hsu"
          tap="tapovs51"
          tun_iface="br0"
          tun_address="192.168.100.13"
          physical_host="banana"
          />
  <switch name="banana-POX2"
          switchType="ovs"
          owner="hsu"
          tap="tapovs52"
          tun_iface="br0"
          tun_address="192.168.100.13"
          physical_host="banana"
          />
  
  <switch name="Amath-Client06-201"
          switchType="ovs"
          owner="hsu"
          tap="tapovs201"
          tun_iface="br0"
          tun_address="140.120.8.106"
          physical_host="Amath-Client06"
          />
  <switch name="Amath-Client06-202"
          switchType="ovs"
          owner="hsu"
          tap="tapovs202"
          tun_iface="br0"
          tun_address="140.120.8.106"
          physical_host="Amath-Client06"
          />
  <switch name="Amath-Client06-203"
          switchType="ovs"
          owner="hsu"
          tap="tapovs203"
          tun_iface="br0"
          tun_address="140.120.8.106"
          physical_host="Amath-Client06"
          />

  <switch name="Lab-81"
          switchType="ovs"
          owner="hsu"
          tap="tapovs81"
          tun_iface="br0"
          tun_address="192.168.100.20"
          physical_host="Lab"
          />
  <switch name="Lab-82"
          switchType="ovs"
          owner="hsu"
          tap="tapovs82"
          tun_iface="br0"
          tun_address="192.168.100.20"
          physical_host="Lab"
          />
  <switch name="Lab-83"
          switchType="ovs"
          owner="hsu"
          tap="tapovs83"
          tun_iface="br0"
          tun_address="192.168.100.20"
          physical_host="Lab"
          />

  <superclass name="banana_en"
              term="screen"
              virTech="kvm"
              template="ovs-wzy.img"
              size="5120M"
              memory="512M"
              >
  <network name="eth0"
             netmask="255.255.255.192"
             />
    <host name="entrance" physical_host="banana">
      <network name="eth0" 
               address="140.120.15.175"
               gateway="140.120.15.171"
               switch="banana-entrance"        
               />
    </host>
  </superclass>

  <superclass name="banana_POX"
              term="screen"
              virTech="kvm"
              template="POX.img"
              size="5120M"
              memory="1024M"
              vcpu="2"
              >
  <network name="eth0"
             netmask="255.255.255.0"
             />
    <host name="POX1" physical_host="banana">
      <network name="eth0" 
               address="192.168.100.51"
               gateway="192.168.100.13"
               switch="banana-POX1"        
               />
    </host>

    <host name="POX2" physical_host="banana">
      <network name="eth0" 
               address="192.168.100.52"
               gateway="192.168.100.13"
               switch="banana-POX2"        
               />
    </host>
  </superclass>  
  
  <superclass name="Amath-Client06"
              term="screen"
              virTech="kvm"
              template="http.img"
              size="5120M"
              memory="512M"
              >
    <network name="eth0"
             netmask="255.255.255.0"
             />

    <host name="http-01" physical_host="Amath-Client06">
      <network name="eth0" 
               address="140.120.8.201"
               gateway="140.120.8.106"
               switch="Amath-Client06-201"        
               />
    </host>

    <host name="http-02" physical_host="Amath-Client06">
      <network name="eth0" 
               address="140.120.8.202"
               gateway="140.120.8.106"
               switch="Amath-Client06-202"        
               />
    </host>

    <host name="http-03" physical_host="Amath-Client06">
      <network name="eth0" 
               address="140.120.8.203"
               gateway="140.120.8.106"
               switch="Amath-Client06-203"        
               />
    </host>
  </superclass>

  <superclass name="Lab"
              term="screen"
              virTech="kvm"
              template="ssh.img"
              size="5120M"
              memory="512M"
              >
    <network name="eth0"
             netmask="255.255.255.0"
             />

    <host name="ssh-01" physical_host="Lab">
      <network name="eth0" 
               address="192.168.100.81"
               gateway="192.168.100.20"
               switch="Lab-81"        
               />
    </host>

    <host name="ssh-02" physical_host="Lab">
      <network name="eth0" 
               address="192.168.100.82"
               gateway="192.168.100.20"
               switch="Lab-82"        
               />
    </host>

    <host name="ssh-03" physical_host="Lab">
      <network name="eth0" 
               address="192.168.100.83"
               gateway="192.168.100.20"
               switch="Lab-83"        
               />
    </host>
  </superclass>  

</project>
